apiVersion: v1
kind: Secret
metadata:
  name: cofrap-secrets
  namespace: cofrap
type: Opaque
stringData:
  ENCRYPTION_KEY: "Rt9LIv0sl8hVk_UjrxDB2QoACvrPoJmVVxuM5OdM5_o="
  DATABASE_URL: "postgresql://cofrap:cofrap@postgres.cofrap.svc.cluster.local:5432/cofrap"
