apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: cofrap
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        mfa VARCHAR(100) DEFAULT '',
        gendate DATE NOT NULL,
        expired INTEGER NOT NULL DEFAULT 0
    );
